<a href="https://colab.research.google.com/github/yesolee/BigDataCertification/blob/main/%EB%B9%85%EB%B6%84%EA%B8%B0_%EC%9E%91%EC%97%85%ED%98%953_titanic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df= pd.read_csv('train_titanic.csv')
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [10]:
df['Sex'].isna().sum(), df['Survived'].isna().sum()

(0, 0)

In [9]:
df['Survived'].isna().sum()

0

In [11]:
contingency_table = pd.crosstab(df['Sex'], df['Survived'])
contingency_table

Survived    0    1
Sex
female     81  233
male      468  109

In [13]:
from scipy.stats import chi2_contingency

chi2, p_value, dof, expected = chi2_contingency(contingency_table)
print(chi2, p_value, dof, expected)

260.71702016732104 1.1973570627755645e-58 1 [[193.47474747 120.52525253]
 [355.52525253 221.47474747]]

In [15]:
np.round(chi2,3)

260.717

In [16]:
 expected

array([[193.47474747, 120.52525253],
       [355.52525253, 221.47474747]])

In [21]:
X = df[['Sex', 'SibSp','Parch','Fare']]
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Sex     891 non-null    object
 1   SibSp   891 non-null    int64
 2   Parch   891 non-null    int64
 3   Fare    891 non-null    float64
dtypes: float64(1), int64(2), object(1)
memory usage: 28.0+ KB

In [22]:
X['Sex'] = X['Sex'].map({'male':0, 'female':1})
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Sex     891 non-null    int64
 1   SibSp   891 non-null    int64
 2   Parch   891 non-null    int64
 3   Fare    891 non-null    float64
dtypes: float64(1), int64(3)
memory usage: 28.0 KB

<ipython-input-22-c11614c3e6dd>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X['Sex'] = X['Sex'].map({'male':0, 'female':1})

In [27]:
y = df['Survived']

import statsmodels.api as sm
X = sm.add_constant(X)

logit_model = sm.Logit(y, X)
result = logit_model.fit()
print(result.summary())

Optimization terminated successfully.
         Current function value: 0.482065
         Iterations 6
                           Logit Regression Results
==============================================================================
Dep. Variable:               Survived   No. Observations:                  891
Model:                          Logit   Df Residuals:                      886
Method:                           MLE   Df Model:                            4
Date:                Tue, 19 Nov 2024   Pseudo R-squ.:                  0.2761
Time:                        09:57:22   Log-Likelihood:                -429.52
converged:                       True   LL-Null:                       -593.33
Covariance Type:            nonrobust   LLR p-value:                 1.192e-69
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const         -1.6956      0.129    -13.098      0.000      -1.949      -1.442
Sex            2.6422      0.186     14.197      0.000       2.277       3.007
SibSp         -0.3539      0.098     -3.604      0.000      -0.546      -0.161
Parch         -0.2007      0.112     -1.792      0.073      -0.420       0.019
Fare           0.0147      0.003      5.553      0.000       0.010       0.020
==============================================================================

In [30]:
print(np.round(result.params['Parch'],3))

-0.201

In [31]:
print(np.round(np.exp(result.params['SibSp']),3))

0.702